### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vido89** [armijnhemel/binaryanalysis#6]
Im getting and error on ubuntu 16.04
```

$ bat-scan -c bat-scan.config -b ~/Downloads/T2/U/usb_backup_upgrade.bin -o TEST
output file already exists
slobodan@G31M-ES2L:~/binaryanalysis/src$ bat-scan -c bat-scan.config -b ~/Downloads/T2/U/usb_backup_upgrade.bin -o Test
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bat/bruteforcescan.py", line 650, in scan
    scanres = locals()["bat_%s" % method](filetoscan, tempdir, blacklist, offsets, newenv, debug=debug)
  File "/usr/local/lib/python2.7/dist-packages/bat/fwunpack.py", line 1902, in searchUnpackYaffs2
    yaffsres = unpackYaffs(filename, offset, tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/bat/fwunpack.py", line 1929, in unpackYaffs
    p = subprocess.Popen(['bat-unyaffs', '-b', filename, '-d', tmpdir, '-j', '-n', '%d' % offset], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by armijnhemel** [comment]
you need to install bat-extratools as well: https://github.com/armijnhemel/bat-extratools/

Please note that this whole project has been abandoned and no more work is being done on it.

**Comment by markusschaber** [comment]
@vido89 JFYI: There are some forks (See https://github.com/armijnhemel/binaryanalysis/network) including one where I'm involved, which try to preserve this project, including some improvements.

**Comment by armijnhemel** [comment]
Thanks Markus. I will add a note about that :)

**Comment by vido89** [comment]
@markusschaber Tnx @armijnhemel I will check that tnx
